# Project information
site_name: iWiki
site_description: weiyong1024的个人博客
site_author: weiyong1024
site_url: https://weiyong.org
strict: true

# Repository
repo_name: 'weiyong1024/iWiki'
repo_url: 'https://github.com/weiyong1024/iWiki'
edit_uri: ''

# Copyright
copyright: Copyright &copy; Yong Wei 2020

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  features:
    tabs: true

# Page tree
nav:
  - 简介: index.md
  - 算法竞赛:
    - 基础:
      - 搜索:
        - 二分搜索: competitive_programming/basic/searching/binary_search.md
        - 三分搜索: competitive_programming/basic/searching/ternary_search.md
      - 排序:
        - 快速排序: competitive_programming/basic/sorting/quick_sort.md
        - 归并排序: competitive_programming/basic/sorting/merge_sort.md
        - 基数排序: competitive_programming/basic/sorting/radix_sort.md
      - 单调栈: competitive_programming/basic/monotune_stack.md
    - 数学:
      - 最大公约数: competitive_programming/math/greatest_common_devisor.md
      - 快速幂: competitive_programming/math/quick_power.md
      - 组合数: competitive_programming/math/combination.md
      - 乘法逆元: competitive_programming/math/inverse.md
      - 埃拉托色尼筛: competitive_programming/math/eratosthenes.md
      - 卡特兰数: competitive_programming/math/catalan_number.md
    - 字符串:
      - Z 函数（扩展KMP）: competitive_programming/string/z-func.md
      - 字典树: competitive_programming/string/trie.md
      - 后缀自动机: competitive_programming/string/suffix_automation.md
      - 后缀数组: competitive_programming/string/suffix_array.md
    - 数据结构:
      - 树状数组: competitive_programming/data_structure/fenwick.md
      - 线段树: competitive_programming/data_structure/segment_tree.md
      - 并查集: competitive_programming/data_structure/union_find.md
      - LRU缓存: competitive_programming/data_structure/lru_cache.md
      - 跳表: competitive_programming/data_structure/skiplist.md
      - B树: competitive_programming/data_structure/btree.md
    - 图论:
      - 最短路径:
        - 单源最短路: competitive_programming/graph_theory/dijkstra.md
        - 所有点对之间最短路: competitive_programming/graph_theory/floyd.md
      - 最小生成树: competitive_programming/graph_theory/minimum_spanning_tree.md
      - 二分图匹配: competitive_programming/graph_theory/bipartite_matching.md
    - 大数据算法:
      - 布隆过滤器: competitive_programming/big_data/bloom_filter.md
  - 设计模式:
    - 对象与接口: design_pattern/object_and_interface.md
    - 算法拆分 - 分离步骤: design_pattern/split_steps.md
    - 算法拆分 - 分离表示: design_pattern/split_representation.md
    - 接口组合: design_pattern/compose_interfaces.md
    - 增加抽象层级: design_pattern/add_layers.md
  - 编程语言:
    - C++:
      - 基础梳理: languages/cpp/basic.md
      - 并发编程: languages/cpp/concurrency.md
      - Effective C++: languages/cpp/effective_cpp.md
    - Java:
      - 概述: languages/java/index.md
      - 基础梳理:
        - Java 历史简介: languages/java/basic/history.md
        - 简单的 Java 程序: languages/java/basic/programming_basic.md
        - 基本语法: languages/java/basic/grammar.md
        - 类、包和接口: languages/java/basic/class_package_interface.md
        - 异常机制: languages/java/basic/exception.md
        - 工具类及常用算法: languages/java/basic/tools_and_algorithm.md
        - 多线程: languages/java/basic/multi_thread.md
        - 文件与流: languages/java/basic/file_and_stream.md
  - 操作系统:
    - 概述: operating_system/index.md
    - 基础梳理:
      - 进程管理: operating_system/basic/process_management.md
      - 内存管理: operating_system/basic/memory_management.md
      - 存储管理: operating_system/basic/storage_management.md
  - 计算机网络:
    - 科学上网: network/sciencetific_surfing.md
  - 机器学习: machine_learning/index.md
  - 经济学原理: 
    - 微观经济学: economics/micro_economics.md
    - 宏观经济学: economics/macro_economics.md
  - 开源库解读:
    - 数据库:
      - LevelDB: open_source/database/leveldb.md
      - Redius: open_source/database/redius.md
    - 消息系统:
      - kafka: open_source/message_system/kafka.md
    - 浏览器: 
      - Chromium: open_source/browser/chromium.md
    - 流式计算:
      - Flink: open_source/stream_computing/flink.md
      - Spark: open_source/stream_computing/spark.md
      - Storm: open_source/stream_computing/storm.md
    - 流量控制:
      - Sentinel: open_source/traffic_control/sentinel.md
    - RPC:
      - Dubbo: open_source/rpc/dubbo.md
  - 技术调研:
    - 大数据架构:
      - Hadoop生态: survey/big_data/hadoop.md
    - 推荐系统:
      - 基础知识: survey/recommendor_system/basic.md
    - Serverless:
      - 基础知识: survey/serverless/basic.md
    - 杂项:
      - CDN: survey/extra/cdn.md
  - 行业观察:
    - 读书笔记:
      - 书单: industry/reading/reading_list.md
    - 财务报表:
      - 微软: industry/fiscal/microsoft/2019_annual_report.md
      - 苹果: industry/fiscal/apple/2019_annual_report.md
      - 亚马逊: industry/fiscal/amazon/2019_annual_report.md
      - 谷歌: industry/fiscal/google/2019_annual_report.md
      - 腾讯: industry/fiscal/tencent/2019_annual_report.md
  - 博客推荐: other_blogs.md 
  - 关于作者: about.md

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  disqus: iwiki1024

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  